server:
  port: 80
#  address: 192.168.1.100
spring:
  main:
    banner-mode: "console"
  profiles:
    active: dev
  redis:
    host: 123.57.219.113
    database: 0
    password:

debug: true
logging:
  path: \github\spring-core\spring-boot-study\log
  level:
      root: INFO
#trace: true

---
spring:
    profiles: dev
server:
    address: 127.0.0.1
---
spring:
    profiles: main
server:
    address: 192.168.0.100

# JPA
#spring:
#  data:
#    jpa:
#      repositories:
#        enabled: true