server:
  port: 8088
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/759796385/spring-cloud-config-server.git
          username:
          password: