server:
  port: 80
spring:
  main:
    banner-mode: "console"
  redis:
    host: 123.57.219.113
    database: 15
    password:
#trace: true



security:
  oauth2:
    resource:
      filter-order: 3


